services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app:create_app
      - FLASK_ENV=development
    volumes:
      - .:/usr/src/app
      - ./data:/usr/src/app/data
